import io.github.kdroidfilter.nucleus.desktop.application.dsl.TargetFormat

abstract class VersionTask : Sync() {
    @get:Input
    abstract val packageString: Property<String>

    @get:Input
    abstract val version: Property<String>

    fun store(resourceHandler: ResourceHandler) {
        from(
            resourceHandler.text.fromString(
                """
                    // Autogenerated. Do not edit!
                    package ${packageString.get().trim()}

                    const val VERSION = "${version.get()}"
                """.trimIndent().trim()
            )
        ) {
            rename { "Version.kt" }
            into(packageString.get().replace('.', '/'))
        }
    }
}

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.kotlinSerialization)
    alias(libs.plugins.aboutlibraries)
    alias(libs.plugins.nucleus)
}

configurations.all {
    resolutionStrategy {
        force(libs.kotlinx.datetime)
    }
}

val appVersion = providers.gradleProperty("app.version").get()

val generateVersion = project.tasks.register<VersionTask>("generateVersion") {
    packageString.set("com.mikepenz.agentapprover")
    version.set(appVersion)
    store(resources)
    into(layout.buildDirectory.dir("generated-version/kotlin/"))
}

kotlin {
    jvm()

    sourceSets {
        commonMain {
            kotlin.srcDir(generateVersion)
        }
        @Suppress("DEPRECATION")
        commonMain.dependencies {
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material3)
            implementation(compose.ui)
            implementation(compose.components.resources)
            implementation(libs.kotlinx.coroutines.core)
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.kotlinx.datetime)
            implementation(libs.kermit)
            implementation(libs.aboutlibraries.core)
            implementation(libs.aboutlibraries.compose.m3)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }
        jvmTest.dependencies {
            implementation(libs.kotlin.test)
        }
        jvmMain.dependencies {
            implementation(compose.desktop.currentOs)
            implementation(libs.kotlinx.coroutines.swing)
            implementation(libs.ktor.server.core)
            implementation(libs.ktor.server.netty)
            implementation(libs.ktor.server.content.negotiation)
            implementation(libs.ktor.serialization.kotlinx.json)
            implementation(libs.markdown.renderer)
            implementation(libs.markdown.renderer.code)
            implementation(libs.nucleus.decorated.window.core)
            implementation(libs.nucleus.decorated.window.jni)
            implementation(libs.nucleus.decorated.window.material)
        }
    }
}


aboutLibraries {
    export {
        outputPath = file("src/commonMain/composeResources/files/aboutlibraries.json")
    }
    library {
        duplicationMode = com.mikepenz.aboutlibraries.plugin.DuplicateMode.MERGE
    }
}

nucleus.application {
    mainClass = "com.mikepenz.agentapprover.MainKt"

    nativeDistributions {
        targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
        packageName = "AgentApprover"
        packageVersion = appVersion
        description = "Centralized approval UI for AI agent tool requests"
        vendor = "mikepenz"

        cleanupNativeLibs = true

        macOS {
            iconFile.set(project.file("../icons/app.icns"))
            layeredIconDir.set(project.file("../icons/AgentApprover.icon"))
            bundleID = "com.mikepenz.agentapprover"
            dockName = "Agent Approver"
            appCategory = "public.app-category.developer-tools"
        }
        windows {
            iconFile.set(project.file("../icons/app.ico"))
            console = false
            perUserInstall = true
        }
        linux {
            iconFile.set(project.file("../icons/app.png"))
        }
    }
}
