name: CI

on:
  push:
    tags:
      - '*'
  pull_request:

jobs:
  build:
    name: Build
    runs-on: macos-latest
    permissions:
      contents: write
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 100

      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v6

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build
        run: ./gradlew :composeApp:jvmJar --stacktrace

      - name: Run Tests
        run: ./gradlew :composeApp:jvmTest --stacktrace

      - name: Publish Test Report
        if: (failure() || success()) && github.event_name == 'pull_request'
        uses: mikepenz/action-junit-report@v6
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_failure: true
          annotate_only: true
          detailed_summary: true

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v6
        if: startsWith(github.ref, 'refs/tags/')
        with:
          ignorePreReleases: ${{ !contains(github.ref, '-') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: mikepenz/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: ${{steps.github_release.outputs.changelog}}
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-b') || contains(github.ref, '-a') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
